# Generated by Django 3.2.8 on 2021-10-07 09:25

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('participant', '0002_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 10, 7, 9, 25, 4, 3863, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='results',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='test',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='test',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
